/* ── Shared job data ─────────────────────────────────────────────── */
/* Single source of truth consumed by Browse Jobs + Job Detail pages  */

export const ALL_JOBS = [
  {
    id: 1,
    company: "Figma",
    initials: "Fi",
    title: "Senior Product Designer",
    location: "San Francisco, CA",
    type: "Full-time",
    category: "Design",
    salary: "$130K – $160K",
    salaryMin: 130,
    salaryMax: 160,
    daysAgo: 1,
    closing: false,
    deadline: "Jul 15, 2026",
    website: "https://figma.com",
    industry: "Design Tools / SaaS",
    employees: "1,000 – 5,000",
    overview: `Figma is looking for a Senior Product Designer to join our growing design system team. You'll define and ship pixel-perfect experiences across web and mobile, collaborating closely with product managers and engineers to turn complex problems into elegant, accessible interfaces.\n\nThis role sits at the heart of how millions of designers experience Figma every day. You'll own end-to-end design for a key product surface, from early concept exploration through final handoff, and contribute to shared design system foundations used across the company.`,
    requirements: [
      "5+ years of product design experience, ideally in B2B SaaS",
      "Expert-level proficiency in Figma (naturally)",
      "Deep portfolio showing systems thinking and interaction design",
      "Experience running and synthesising user research",
      "Ability to write specs and documentation for complex interactions",
      "Comfortable working in a high-autonomy, async-first environment",
      "Strong cross-functional collaboration skills with engineering and PM",
    ],
    niceToHave: [
      "Prior experience designing for developer or creator tooling",
      "Contributions to open-source design systems",
      "Familiarity with accessibility standards (WCAG 2.2)",
      "Experience conducting usability testing",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Competitive salary + equity",
        detail: "Top-of-market comp with meaningful equity grants",
      },
      {
        icon: "🏥",
        label: "Full health coverage",
        detail: "Medical, dental, and vision for you and dependants",
      },
      {
        icon: "🏖️",
        label: "Unlimited PTO",
        detail: "Flexible time off with a minimum 15-day policy",
      },
      {
        icon: "📚",
        label: "$2,000 learning budget",
        detail: "Annual stipend for courses, books, and conferences",
      },
      {
        icon: "🌍",
        label: "Remote-friendly",
        detail: "Hybrid with full flexibility after onboarding",
      },
      {
        icon: "🍔",
        label: "Daily catered lunch",
        detail: "On-site meals at SF HQ, DoorDash credit for remote",
      },
    ],
  },
  {
    id: 2,
    company: "Vercel",
    initials: "Ve",
    title: "AI Platform Engineer",
    location: "Remote · Global",
    type: "Full-time",
    category: "Engineering",
    salary: "$150K – $185K",
    salaryMin: 150,
    salaryMax: 185,
    daysAgo: 0,
    closing: false,
    deadline: "Jul 31, 2026",
    website: "https://vercel.com",
    industry: "Cloud Infrastructure / Developer Tools",
    employees: "500 – 1,000",
    overview: `Vercel is building the AI-native deployment platform. As an AI Platform Engineer you'll architect and scale the runtime pipeline that takes prompts from developers all the way to production edge deployments — used by over a million developers worldwide.\n\nYou'll work alongside a world-class distributed systems team, owning the full lifecycle of AI features: from prototyping serverless AI execution environments to hardening them for global scale.`,
    requirements: [
      "4+ years of backend engineering experience",
      "Strong understanding of distributed systems and cloud infrastructure",
      "Experience building and scaling LLM-backed APIs",
      "Proficiency in TypeScript and Node.js (Rust a big plus)",
      "Hands-on experience with Kubernetes or similar orchestration",
      "Deep familiarity with edge networking concepts",
    ],
    niceToHave: [
      "Prior work on serverless or edge compute platforms",
      "Open source contributions in the JS/TS ecosystem",
      "Experience with AI observability tooling",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Equity-heavy comp",
        detail: "Generous stock options with 4-year vest",
      },
      {
        icon: "🌍",
        label: "Fully remote",
        detail: "Work from anywhere — we mean it",
      },
      {
        icon: "🏥",
        label: "Health, dental, vision",
        detail: "100% employer-paid premiums",
      },
      {
        icon: "🖥️",
        label: "$4,000 home office budget",
        detail: "Get the setup you need to do your best work",
      },
      {
        icon: "📚",
        label: "Unlimited learning",
        detail: "Conferences, courses, anything that helps you grow",
      },
      {
        icon: "🚀",
        label: "Async-first culture",
        detail: "Deep work over meetings, documentation over syncs",
      },
    ],
  },
  {
    id: 3,
    company: "Linear",
    initials: "Li",
    title: "DevOps Engineer",
    location: "New York, NY",
    type: "Contract",
    category: "DevOps",
    salary: "$120K – $148K",
    salaryMin: 120,
    salaryMax: 148,
    daysAgo: 5,
    closing: true,
    deadline: "Jun 20, 2026",
    website: "https://linear.app",
    industry: "Project Management / SaaS",
    employees: "50 – 200",
    overview: `Linear builds the project management tool engineered for speed. We're looking for a DevOps Engineer to architect CI/CD pipelines, manage Kubernetes clusters, and ensure 99.99% uptime for a fast-growing SaaS product used by thousands of engineering teams.\n\nYou'll be a core infrastructure contributor in a small, high-trust environment — owning reliability, observability, and deployment tooling end-to-end.`,
    requirements: [
      "4+ years of DevOps or Site Reliability Engineering experience",
      "Expert Kubernetes administration and Helm chart authoring",
      "Strong experience with Terraform or Pulumi for IaC",
      "CI/CD pipeline design (GitHub Actions, Buildkite, or similar)",
      "Observability stack ownership (Datadog, Grafana, PagerDuty)",
      "Experience with PostgreSQL at scale",
    ],
    niceToHave: [
      "Background in early-stage startup infrastructure",
      "Experience with Cloudflare Workers / edge routing",
      "Security hardening and SOC 2 compliance",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Competitive contract rate",
        detail: "Hourly rate negotiated based on experience",
      },
      {
        icon: "🏖️",
        label: "Flexible schedule",
        detail: "Core hours with flexible start and end times",
      },
      {
        icon: "🖥️",
        label: "Equipment provided",
        detail: "MacBook Pro + peripherals shipped on day one",
      },
      {
        icon: "🚀",
        label: "High-impact work",
        detail: "Small team, big ownership, direct impact on product",
      },
    ],
  },
  {
    id: 4,
    company: "Stripe",
    initials: "St",
    title: "Backend Engineer – Payments",
    location: "Dublin, Ireland",
    type: "Full-time",
    category: "Engineering",
    salary: "$140K – $175K",
    salaryMin: 140,
    salaryMax: 175,
    daysAgo: 7,
    closing: false,
    deadline: "Aug 10, 2026",
    website: "https://stripe.com",
    industry: "Fintech / Payments",
    employees: "8,000+",
    overview: `Stripe's mission is economic infrastructure for the internet. As a Backend Engineer on the Payments team in Dublin, you'll develop the highly reliable services that move billions of dollars for millions of businesses around the world.\n\nYou'll work with a team of exceptional engineers on the core payments processing systems, balancing performance, reliability, and compliance requirements across dozens of global markets.`,
    requirements: [
      "5+ years of backend engineering experience",
      "Deep experience with distributed systems and microservices",
      "Proficiency in Ruby, Java, Go, or Scala",
      "Strong understanding of financial systems and double-entry bookkeeping",
      "Experience with high-throughput, low-latency services",
      "Rigorous approach to testing, observability, and incident response",
    ],
    niceToHave: [
      "Prior work in payments, banking, or fintech",
      "Experience with PCI-DSS compliance",
      "Familiarity with card network protocols (Visa, Mastercard)",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Top-of-market salary + RSUs",
        detail: "Highly competitive total comp with quarterly vest",
      },
      {
        icon: "🏥",
        label: "Comprehensive health",
        detail: "Full family medical, dental, vision, and life insurance",
      },
      {
        icon: "🌍",
        label: "Relocation support",
        detail: "Full relocation package for candidates moving to Dublin",
      },
      {
        icon: "🍔",
        label: "On-site amenities",
        detail: "Daily meals, coffee bar, gym at Dublin HQ",
      },
      {
        icon: "📚",
        label: "Learning & development",
        detail: "Dedicated budget + internal learning platform",
      },
      {
        icon: "🏖️",
        label: "25 days PTO",
        detail: "Plus public holidays and sabbatical after 5 years",
      },
    ],
  },
  {
    id: 5,
    company: "Notion",
    initials: "No",
    title: "Growth Marketing Manager",
    location: "Remote · US",
    type: "Full-time",
    category: "Marketing",
    salary: "$110K – $135K",
    salaryMin: 110,
    salaryMax: 135,
    daysAgo: 2,
    closing: false,
    deadline: "Jul 25, 2026",
    website: "https://notion.so",
    industry: "Productivity / SaaS",
    employees: "500 – 1,000",
    overview: `Notion is looking for a Growth Marketing Manager to own acquisition and activation across paid, SEO, and lifecycle channels. You'll run experiments, measure impact, and turn data-driven insights into campaigns that meaningfully move product growth metrics.\n\nYou'll partner closely with product, design, data, and sales to craft the full funnel — from first impression to power user.`,
    requirements: [
      "4+ years of growth or performance marketing experience",
      "Strong analytical skills and fluency with SQL or BI tools",
      "Proven track record running A/B experiments at scale",
      "Experience with paid acquisition (Google, Meta, LinkedIn)",
      "Hands-on SEO and content strategy background",
      "CRM and lifecycle marketing experience (HubSpot, Braze, or Iterable)",
    ],
    niceToHave: [
      "PLG (product-led growth) experience at a B2B SaaS company",
      "Familiarity with attribution modelling",
      "Prior work on viral or referral loop mechanics",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Competitive salary + equity",
        detail: "Market-rate with meaningful stock options",
      },
      {
        icon: "🌍",
        label: "Remote-first",
        detail: "Work from anywhere in the US",
      },
      {
        icon: "🏥",
        label: "Full health coverage",
        detail: "Medical, dental, vision for you and family",
      },
      {
        icon: "🍔",
        label: "Meal & wellness stipend",
        detail: "$150/month for food, $100/month for wellness",
      },
      {
        icon: "📚",
        label: "Learning stipend",
        detail: "$1,500/year for courses and conferences",
      },
    ],
  },
  {
    id: 6,
    company: "Loom",
    initials: "Lo",
    title: "iOS Engineer",
    location: "Austin, TX",
    type: "Part-time",
    category: "Engineering",
    salary: "$125K – $155K",
    salaryMin: 125,
    salaryMax: 155,
    daysAgo: 12,
    closing: false,
    deadline: "Aug 5, 2026",
    website: "https://loom.com",
    industry: "Video Communication / SaaS",
    employees: "200 – 500",
    overview: `Loom is the async video messaging tool used by millions of teams. We're hiring an iOS Engineer to build smooth, performant video recording and playback features in Swift — shaping the mobile experience for communicators worldwide.\n\nYou'll own key features in the iOS app, collaborating with a cross-platform mobile team and working directly with product and design on what's next.`,
    requirements: [
      "3+ years of native iOS development",
      "Expert Swift and UIKit / SwiftUI",
      "Experience with AVFoundation for audio/video",
      "Strong understanding of iOS app lifecycle and performance profiling",
      "Familiarity with Swift concurrency (async/await, actors)",
      "Experience shipping apps to the App Store",
    ],
    niceToHave: [
      "React Native or cross-platform mobile experience",
      "Background in media streaming or real-time communication apps",
      "Experience with Core ML or on-device AI",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Part-time competitive rate",
        detail: "Pro-rated salary based on hours",
      },
      {
        icon: "🖥️",
        label: "Latest Apple hardware",
        detail: "MacBook Pro M-series + iPhone for testing",
      },
      {
        icon: "🏖️",
        label: "Flexible schedule",
        detail: "Set your own hours, async by default",
      },
      {
        icon: "📚",
        label: "WWDC attendance",
        detail: "Annual Apple developer conference sponsored",
      },
    ],
  },
  {
    id: 7,
    company: "Shopify",
    initials: "Sh",
    title: "Data Scientist – Commerce",
    location: "Remote · Canada",
    type: "Full-time",
    category: "Data & Analytics",
    salary: "$135K – $165K",
    salaryMin: 135,
    salaryMax: 165,
    daysAgo: 1,
    closing: false,
    deadline: "Aug 1, 2026",
    website: "https://shopify.com",
    industry: "E-Commerce / Platform",
    employees: "10,000+",
    overview: `Shopify powers commerce for over 2 million merchants. As a Data Scientist on the Commerce Intelligence team, you'll build models and analytical frameworks that help merchants grow — from demand forecasting to personalisation to fraud detection.\n\nYou'll work with petabyte-scale data pipelines and have direct influence on product decisions affecting millions of businesses.`,
    requirements: [
      "4+ years of data science or ML engineering experience",
      "Strong Python and SQL — pandas, scikit-learn, dbt",
      "Experience deploying ML models to production",
      "Solid statistical foundations: A/B testing, causal inference",
      "Experience with Spark or distributed data processing",
      "Ability to communicate complex findings to non-technical stakeholders",
    ],
    niceToHave: [
      "E-commerce or marketplace domain expertise",
      "Experience with LLM fine-tuning or retrieval-augmented systems",
      "Background in time-series forecasting",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Top-of-market comp + RSUs",
        detail: "Strong base + equity refreshes",
      },
      {
        icon: "🌍",
        label: "Fully remote (Canada)",
        detail: "Work from any province",
      },
      {
        icon: "🏥",
        label: "Extended health benefits",
        detail: "Full family coverage including mental health",
      },
      {
        icon: "📚",
        label: "$2,500 development budget",
        detail: "Books, courses, tools — no approval needed",
      },
      { icon: "🏖️", label: "Flexible PTO", detail: "Take the time you need" },
    ],
  },
  {
    id: 8,
    company: "Atlassian",
    initials: "At",
    title: "Product Manager, Jira",
    location: "Sydney, Australia",
    type: "Full-time",
    category: "Product",
    salary: "$120K – $155K",
    salaryMin: 120,
    salaryMax: 155,
    daysAgo: 3,
    closing: true,
    deadline: "Jun 18, 2026",
    website: "https://atlassian.com",
    industry: "Project Management / SaaS",
    employees: "10,000+",
    overview: `Atlassian is looking for a Product Manager to join the Jira team in Sydney. You'll own a key area of Jira's core experience, defining strategy, writing specs, and partnering with engineering and design to ship features used by millions of teams every day.\n\nThis role requires strong product instincts, deep empathy for developers and project teams, and the ability to navigate a complex, high-scale product.`,
    requirements: [
      "5+ years of product management experience in B2B SaaS",
      "Proven ability to define strategy and ship at scale",
      "Strong analytical skills — comfortable with data and metrics",
      "Excellent written communication for async-first environment",
      "Experience working closely with engineering on complex technical features",
    ],
    niceToHave: [
      "Experience as a software developer or engineering manager",
      "Background in project management or agile tooling",
      "Prior work at a high-scale consumer or enterprise product",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Competitive salary + equity",
        detail: "Market comp with RSU grants",
      },
      {
        icon: "🏥",
        label: "Full health & wellness",
        detail: "Medical, dental, vision + mental health support",
      },
      {
        icon: "🍔",
        label: "Daily meals at HQ",
        detail: "Full catering at Sydney office",
      },
      {
        icon: "📚",
        label: "Learning & growth",
        detail: "Internal university + external conference budget",
      },
      {
        icon: "🌍",
        label: "Hybrid work",
        detail: "3 days in-office, 2 days remote",
      },
    ],
  },
  {
    id: 9,
    company: "GitHub",
    initials: "Gh",
    title: "Developer Relations Engineer",
    location: "Remote · Global",
    type: "Full-time",
    category: "Engineering",
    salary: "$115K – $145K",
    salaryMin: 115,
    salaryMax: 145,
    daysAgo: 9,
    closing: false,
    deadline: "Aug 20, 2026",
    website: "https://github.com",
    industry: "Developer Tools / Microsoft",
    employees: "3,000 – 5,000",
    overview: `GitHub is looking for a Developer Relations Engineer to help build and nurture our global developer community. You'll create technical content, speak at conferences, maintain sample repositories, and act as a bridge between developers and GitHub's product teams.\n\nYou'll be the voice of the developer, advocating internally for product improvements while externally championing GitHub's capabilities.`,
    requirements: [
      "3+ years of software engineering experience",
      "Strong public communication skills — writing, speaking, video",
      "Track record of technical content creation (blog posts, talks, demos)",
      "Broad programming knowledge across multiple languages and stacks",
      "Experience contributing to open-source projects",
    ],
    niceToHave: [
      "Experience with GitHub Actions, Copilot, or GitHub Models",
      "Large developer community following",
      "Background in developer education or bootcamp instruction",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Microsoft total comp",
        detail: "Base + RSUs + annual bonus",
      },
      { icon: "🌍", label: "Fully remote", detail: "Anywhere in the world" },
      {
        icon: "✈️",
        label: "Conference travel",
        detail: "Full budget to speak at global events",
      },
      {
        icon: "🏥",
        label: "Full health benefits",
        detail: "Comprehensive medical + mental health",
      },
      {
        icon: "📚",
        label: "Learning budget",
        detail: "$3,000/year for continued education",
      },
    ],
  },
  {
    id: 10,
    company: "HubSpot",
    initials: "Hu",
    title: "Senior Sales Engineer",
    location: "Boston, MA",
    type: "Full-time",
    category: "Sales",
    salary: "$105K – $130K",
    salaryMin: 105,
    salaryMax: 130,
    daysAgo: 0,
    closing: false,
    deadline: "Jul 28, 2026",
    website: "https://hubspot.com",
    industry: "CRM / Marketing Automation",
    employees: "7,000+",
    overview: `HubSpot is hiring a Senior Sales Engineer to join the enterprise growth team in Boston. You'll partner with AEs on complex deals, run technical discovery, deliver tailored product demos, and architect solutions for mid-market and enterprise prospects.\n\nYou'll be the technical authority in the sales cycle, building confidence with engineering and IT stakeholders at prospective customers.`,
    requirements: [
      "4+ years of sales engineering or solutions consulting experience",
      "Strong technical breadth across web, APIs, and integrations",
      "Excellent presentation and demo skills",
      "Experience working on enterprise sales cycles (6–12 months)",
      "Familiarity with CRM, marketing automation, or RevOps tooling",
    ],
    niceToHave: [
      "Prior experience as a software developer",
      "Salesforce, Marketo, or competitive CRM knowledge",
      "Background in SaaS sales methodology (MEDDIC, SPIN)",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Base + commission",
        detail: "Uncapped commission on top of strong base",
      },
      {
        icon: "🏥",
        label: "Full health coverage",
        detail: "Medical, dental, vision, and FSA",
      },
      {
        icon: "🍔",
        label: "Free lunch daily",
        detail: "Catered meals at Boston HQ",
      },
      {
        icon: "🏖️",
        label: "Unlimited PTO",
        detail: "With enforced minimum of 15 days",
      },
      {
        icon: "📚",
        label: "Tuition reimbursement",
        detail: "Up to $5,000/year for continuing education",
      },
    ],
  },
  {
    id: 11,
    company: "Twilio",
    initials: "Tw",
    title: "Solutions Architect",
    location: "San Francisco, CA",
    type: "Contract",
    category: "Engineering",
    salary: "$145K – $175K",
    salaryMin: 145,
    salaryMax: 175,
    daysAgo: 6,
    closing: false,
    deadline: "Aug 15, 2026",
    website: "https://twilio.com",
    industry: "Communications API / CPaaS",
    employees: "5,000 – 8,000",
    overview: `Twilio's mission is to make communication programmable. As a Solutions Architect you'll work with Twilio's top-tier customers to design, build, and optimise communication architectures using Twilio's voice, messaging, and video APIs.\n\nYou'll act as a trusted technical partner, running workshops, reviewing architectures, and producing proof-of-concept implementations that accelerate customer success.`,
    requirements: [
      "5+ years in solutions architecture, professional services, or senior software engineering",
      "Deep API and integration knowledge across REST, webhooks, and event-driven systems",
      "Experience with cloud platforms (AWS, GCP, or Azure)",
      "Strong communication and client-facing skills",
      "Ability to prototype quickly in Python, Node.js, or Java",
    ],
    niceToHave: [
      "Direct experience with Twilio APIs (Voice, SMS, Flex)",
      "Background in telecom or contact centre technologies",
      "Experience designing for high-availability and failover",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Competitive contract rate",
        detail: "Rates benchmarked to full-time equivalents",
      },
      {
        icon: "🖥️",
        label: "Remote-optional",
        detail: "Hybrid with remote-first flexibility",
      },
      {
        icon: "✈️",
        label: "Customer travel covered",
        detail: "All client site travel fully expensed",
      },
      {
        icon: "📚",
        label: "Certification support",
        detail: "AWS / GCP cert exams fully reimbursed",
      },
    ],
  },
  {
    id: 12,
    company: "Intercom",
    initials: "In",
    title: "Customer Success Lead",
    location: "Dublin, Ireland",
    type: "Full-time",
    category: "Customer Success",
    salary: "$90K – $115K",
    salaryMin: 90,
    salaryMax: 115,
    daysAgo: 14,
    closing: true,
    deadline: "Jun 15, 2026",
    website: "https://intercom.com",
    industry: "Customer Messaging / SaaS",
    employees: "1,000 – 3,000",
    overview: `Intercom is the AI-first customer service platform. We're looking for a Customer Success Lead to manage a portfolio of strategic accounts, drive adoption and retention, and act as a trusted advisor to our most valuable customers.\n\nYou'll work cross-functionally with product, engineering, and sales to ensure customers get maximum value from Intercom's platform.`,
    requirements: [
      "4+ years in customer success, account management, or consulting",
      "Proven track record of driving NRR and expansion revenue",
      "Strong executive communication skills",
      "Experience managing a book of business of $3M+ ARR",
      "Data-driven approach to health scoring and churn prevention",
    ],
    niceToHave: [
      "Background in SaaS customer support or CX products",
      "Experience with Gainsight or Totango",
      "Prior experience at a high-growth Series C+ startup",
    ],
    benefits: [
      {
        icon: "💰",
        label: "Salary + performance bonus",
        detail: "Quarterly retention and expansion bonuses",
      },
      {
        icon: "🏥",
        label: "Health & wellbeing",
        detail: "VHI medical, dental, and wellness fund",
      },
      {
        icon: "🍔",
        label: "Catered meals",
        detail: "Breakfast and lunch at Dublin HQ",
      },
      {
        icon: "🌍",
        label: "Hybrid work",
        detail: "3 days in Dublin office, 2 remote",
      },
      {
        icon: "🏖️",
        label: "25 days PTO",
        detail: "Plus bank holidays and birthday day off",
      },
    ],
  },
];

export function getJobById(id) {
  return ALL_JOBS.find((j) => j.id === Number(id)) ?? null;
}

export function getSimilarJobs(job, count = 3) {
  return ALL_JOBS.filter(
    (j) =>
      j.id !== job.id && (j.category === job.category || j.type === job.type),
  ).slice(0, count);
}
